---
name: Ifeffit-Demeter
version: 0.2.0
author:
  - 'Bruce Ravel <bravel AT bnl DOT gov>'
abstract: An object oriented EXAFS data analysis system using Ifeffit
license: gpl
resources:
  license: http://www.opensource.org/licenses/gpl-license.php
requires:
  Archive::Zip: 0
  Chemistry::Elements: 0
  Digest::SHA: 0
  Heap: 0
  List::MoreUtils: 0
  Math::Cephes: 0
  Math::Derivative: 0
  Math::Round: 0
  Math::Spline: 0
  Module::Build: 0
  Moose: 0
  MooseX::AttributeHelpers: 0
  MooseX::Clone: 0
  MooseX::Singleton: 0
  MooseX::Types: 0
  Readonly: 0
  Regexp::Common: 0
  Regexp::Optimizer: 0
  Text::Template: 0
  Text::Wrap: 0
  Tree::Simple: 0
  Want: 0
  YAML: 0
  version: 0
recommends:
  Graphics::GnuplotIF: 0
  IO::Prompt: 0
  Smart::Comments: 0
  Term::ANSIColor: 0
  Term::ReadLine: 0
  Term::Twiddle: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
